# Generated by Django 4.2.7 on 2023-11-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demanda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
