# Generated by Django 4.2.7 on 2023-11-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demanda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_tecnico',
            field=models.BooleanField(default=False),
        ),
    ]
